services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.express
        container_name: sakay-javascript-api
        ports:
            - '3000'
        env_file: .env
        restart: always
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: sakay-javascript-nginx
        ports:
            - '80:8080'
        depends_on:
            - api
        restart: always
