services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.express
        container_name: sakay-javascript-api
        ports:
            - '3000'
        env_file: .env
        restart: always
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: sakay-javascript-nginx
        ports:
            - '80:8080'
        depends_on:
            - api
        restart: always

    redis:
        image: redis:8.2.2-alpine
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']
        restart: always

    volumes:
        redis_data:
