services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile.flask
        container_name: flask-api
        expose:
            - '5000'
        env_file:
            - .env
        restart: always
        networks:
            - shared_network

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: flask-nginx
        ports:
            - '80:8080'
        depends_on:
            - flask
        restart: always
        networks:
            - shared_network

    celery_worker:
        build:
        context: .
        dockerfile: Dockerfile.celery
        container_name: celery-worker
        env_file:
            - .env
        depends_on:
            - flask
        command: celery -A celery_worker.celery worker --loglevel=info
        restart: always
        networks:
            - shared_network

    celery_beat:
        build:
        context: .
        dockerfile: Dockerfile.celery
        container_name: celery-beat
        env_file:
            - .env
        depends_on:
            - flask
        command: celery -A celery_worker.celery beat --loglevel=info
        restart: always
        networks:
            - shared_network

networks:
    shared_network:
        external: true
