FROM python:3.15.0a1-alpine3.22

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app .

CMD ["celery", "-A", "celery_worker", "worker", "--loglevel=info"]